-- MySQL Script generated by MySQL Workbench
-- Sat Feb 14 15:12:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUser` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Rol` TINYINT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurante` (
  `idRestaurante` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `logo` LONGBLOB NOT NULL,
  PRIMARY KEY (`idRestaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mesas` (
  `idMesas` INT NOT NULL,
  `idRestaurante` INT NOT NULL,
  `NumeroMesa` DECIMAL NOT NULL,
  `Capacidad` DECIMAL NOT NULL,
  `Estado` BINARY(2) NOT NULL,
  PRIMARY KEY (`idMesas`),
  INDEX `idRestaurante_idx` (`idRestaurante` ASC) VISIBLE,
  CONSTRAINT `idRestaurante`
    FOREIGN KEY (`idRestaurante`)
    REFERENCES `mydb`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `FechaHora` DATETIME(6) NOT NULL,
  `Estado` BINARY(3) NOT NULL,
  `idMesas` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `idMesas_idx` (`idMesas` ASC) VISIBLE,
  CONSTRAINT `idMesas`
    FOREIGN KEY (`idMesas`)
    REFERENCES `mydb`.`Mesas` (`idMesas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `ticketID` INT NOT NULL,
  `FechaHora` DATETIME(10) NOT NULL,
  `Total` DECIMAL(10) NOT NULL,
  `Estado` TINYINT NOT NULL,
  `idUser` INT NOT NULL,
  `idPedido` INT NOT NULL,
  `idMesa` INT NULL,
  PRIMARY KEY (`ticketID`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  INDEX `idPedido_idx` (`idPedido` ASC) VISIBLE,
  INDEX `idMesas_idx` (`idMesa` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`Usuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMesas`
    FOREIGN KEY (`idMesa`)
    REFERENCES `mydb`.`Mesas` (`idMesas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `idMenu` INT NOT NULL,
  `idRestaurante` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `Categoria` ENUM('Postre', 'PlatilloPrincipal', 'Entrada') NOT NULL,
  `Disponibilidad` TINYINT NOT NULL,
  PRIMARY KEY (`idMenu`),
  INDEX `idRestaurant_idx` (`idRestaurante` ASC) VISIBLE,
  CONSTRAINT `idRestaurant`
    FOREIGN KEY (`idRestaurante`)
    REFERENCES `mydb`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetallePedido` (
  `idDetallePedido` INT NOT NULL,
  `idMenu` INT NOT NULL,
  `idPedido` INT NOT NULL,
  `Cantidad` DECIMAL NOT NULL,
  `PrecioUnitario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetallePedido`),
  INDEX `idPedido_idx` (`idPedido` ASC) VISIBLE,
  INDEX `idMenu_idx` (`idMenu` ASC) VISIBLE,
  CONSTRAINT `idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMenu`
    FOREIGN KEY (`idMenu`)
    REFERENCES `mydb`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleTicketCompartido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetalleTicketCompartido` (
  `idDetalleTicketCompartido` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idTicket` INT NOT NULL,
  `idDetallePedido` INT NOT NULL,
  `fraccion` INT NOT NULL,
  `montoasignado` INT NOT NULL,
  PRIMARY KEY (`idDetalleTicketCompartido`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  INDEX `idTicket_idx` (`idTicket` ASC) VISIBLE,
  INDEX `idDetallePedido_idx` (`idDetallePedido` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`Usuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTicket`
    FOREIGN KEY (`idTicket`)
    REFERENCES `mydb`.`Ticket` (`ticketID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDetallePedido`
    FOREIGN KEY (`idDetallePedido`)
    REFERENCES `mydb`.`DetallePedido` (`idDetallePedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
